spring.application.name=nutrireceitas-api

# Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/nutrireceitas
spring.datasource.username=postgres
spring.datasource.password=1910
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# CORS - permite o frontend React conectar
spring.web.cors.allowed-origins=http://localhost:3000

# Porta do servidor
server.port=8080
